Build Failure: cribe_server.o: In function `_GLOBAL__sub_I_g_Handler': scribe_server.cpp:(.text.startup+0x703): undefined reference to `boost::system::generic_category()'
Fix:http://wiki.debian.org/ToolChain/DSOLinking#Onlylinkwithneededlibraries
Static linker wants to pull in only what it needs from each included library. But it only knows what it needs based on the symbols it has already loaded and looked at.
 And it only tries to statically link in each library once, when it first sees it.
 --as-needed option also makes the linker sensitive to the ordering of libraries on the command-line.
 You may need to move some libraries later in the command-line, so they come after other libraries or files that require symbols from them