Build Failure: file.cpp: In member function ‘virtual void StdFile::listImpl(const string&, std::vector<std::basic_string<char> >&)’: file.cpp:248:37: error: ‘class boost::filesystem3::directory_entry’ has no member named ‘filename’
Fix: Boost releases 1.44 through 1.47 will supply both V2 and V3. Version 2 is the default version for Boost release 1.44 and 1.45.
Version 3 will be the default starting with release 1.46.
filename() is deprected in v3 and added path().filename() instead
String() is deprected in v3, use path().string() isntead
** we can set BOOST_FILESYSTEM_VERSION = 2 from command line or we can make code changes to use v3